# Generated by Django 5.1.3 on 2024-11-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userdata_groups_userdata_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
